# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.transaction_out import TransactionOut
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DashboardOut(BaseModel):
    """
    DashboardOut
    """ # noqa: E501
    total_income: Union[StrictFloat, StrictInt]
    total_expenses: Union[StrictFloat, StrictInt]
    balance: Union[StrictFloat, StrictInt]
    total_savings: Union[StrictFloat, StrictInt]
    monthly_income: Union[StrictFloat, StrictInt]
    monthly_expenses: Union[StrictFloat, StrictInt]
    carried_savings: Union[StrictFloat, StrictInt]
    total_transactions: StrictInt
    top_spending_category: Optional[StrictStr]
    recent_activity: List[TransactionOut]
    __properties: ClassVar[List[str]] = ["total_income", "total_expenses", "balance", "total_savings", "monthly_income", "monthly_expenses", "carried_savings", "total_transactions", "top_spending_category", "recent_activity"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DashboardOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in recent_activity (list)
        _items = []
        if self.recent_activity:
            for _item_recent_activity in self.recent_activity:
                if _item_recent_activity:
                    _items.append(_item_recent_activity.to_dict())
            _dict['recent_activity'] = _items
        # set to None if top_spending_category (nullable) is None
        # and model_fields_set contains the field
        if self.top_spending_category is None and "top_spending_category" in self.model_fields_set:
            _dict['top_spending_category'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DashboardOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_income": obj.get("total_income"),
            "total_expenses": obj.get("total_expenses"),
            "balance": obj.get("balance"),
            "total_savings": obj.get("total_savings"),
            "monthly_income": obj.get("monthly_income"),
            "monthly_expenses": obj.get("monthly_expenses"),
            "carried_savings": obj.get("carried_savings"),
            "total_transactions": obj.get("total_transactions"),
            "top_spending_category": obj.get("top_spending_category"),
            "recent_activity": [TransactionOut.from_dict(_item) for _item in obj["recent_activity"]] if obj.get("recent_activity") is not None else None
        })
        return _obj


