# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_add_transaction_transactions_post(self) -> None:
        """Test case for add_transaction_transactions_post

        Add Transaction
        """
        pass

    def test_delete_transaction_transactions_transaction_id_delete(self) -> None:
        """Test case for delete_transaction_transactions_transaction_id_delete

        Delete Transaction
        """
        pass

    def test_export_csv_transactions_export_get(self) -> None:
        """Test case for export_csv_transactions_export_get

        Export Csv
        """
        pass

    def test_get_summary_transactions_summary_get(self) -> None:
        """Test case for get_summary_transactions_summary_get

        Get Summary
        """
        pass

    def test_list_transactions_transactions_get(self) -> None:
        """Test case for list_transactions_transactions_get

        List Transactions
        """
        pass

    def test_reclassify_transactions_transaction_id_reclassify_patch(self) -> None:
        """Test case for reclassify_transactions_transaction_id_reclassify_patch

        Reclassify
        """
        pass


if __name__ == '__main__':
    unittest.main()
