# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.savings_transaction_out import SavingsTransactionOut

class TestSavingsTransactionOut(unittest.TestCase):
    """SavingsTransactionOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SavingsTransactionOut:
        """Test SavingsTransactionOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SavingsTransactionOut`
        """
        model = SavingsTransactionOut()
        if include_optional:
            return SavingsTransactionOut(
                id = 56,
                type = '',
                amount = 1.337,
                reason = '',
                goal_id = 56,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return SavingsTransactionOut(
                id = 56,
                type = '',
                amount = 1.337,
                reason = '',
                goal_id = 56,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testSavingsTransactionOut(self):
        """Test SavingsTransactionOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
