# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dashboard_api import DashboardApi


class TestDashboardApi(unittest.TestCase):
    """DashboardApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DashboardApi()

    def tearDown(self) -> None:
        pass

    def test_download_pdf_report_report_pdf_get(self) -> None:
        """Test case for download_pdf_report_report_pdf_get

        Download Pdf Report
        """
        pass

    def test_get_dashboard_dashboard_get(self) -> None:
        """Test case for get_dashboard_dashboard_get

        Get Dashboard
        """
        pass

    def test_get_gamification_stats_gamification_get(self) -> None:
        """Test case for get_gamification_stats_gamification_get

        Get Gamification Stats
        """
        pass

    def test_get_optimization_advice_optimization_get(self) -> None:
        """Test case for get_optimization_advice_optimization_get

        Get Optimization Advice
        """
        pass

    def test_import_transactions_csv_csv_import_post(self) -> None:
        """Test case for import_transactions_csv_csv_import_post

        Import Transactions Csv
        """
        pass


if __name__ == '__main__':
    unittest.main()
