# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.budget_create import BudgetCreate

class TestBudgetCreate(unittest.TestCase):
    """BudgetCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BudgetCreate:
        """Test BudgetCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BudgetCreate`
        """
        model = BudgetCreate()
        if include_optional:
            return BudgetCreate(
                category = '',
                monthly_limit = 1.337
            )
        else:
            return BudgetCreate(
                category = '',
                monthly_limit = 1.337,
        )
        """

    def testBudgetCreate(self):
        """Test BudgetCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
