# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.saving_goal_add import SavingGoalAdd

class TestSavingGoalAdd(unittest.TestCase):
    """SavingGoalAdd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SavingGoalAdd:
        """Test SavingGoalAdd
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SavingGoalAdd`
        """
        model = SavingGoalAdd()
        if include_optional:
            return SavingGoalAdd(
                amount = 1.337
            )
        else:
            return SavingGoalAdd(
                amount = 1.337,
        )
        """

    def testSavingGoalAdd(self):
        """Test SavingGoalAdd"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
