# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.savings_api import SavingsApi


class TestSavingsApi(unittest.TestCase):
    """SavingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SavingsApi()

    def tearDown(self) -> None:
        pass

    def test_add_to_saving_goal_savings_goal_id_add_patch(self) -> None:
        """Test case for add_to_saving_goal_savings_goal_id_add_patch

        Add To Saving Goal
        """
        pass

    def test_create_saving_goal_savings_post(self) -> None:
        """Test case for create_saving_goal_savings_post

        Create Saving Goal
        """
        pass

    def test_deposit_to_savings_savings_deposit_post(self) -> None:
        """Test case for deposit_to_savings_savings_deposit_post

        Deposit To Savings
        """
        pass

    def test_get_savings_balance_savings_balance_get(self) -> None:
        """Test case for get_savings_balance_savings_balance_get

        Get Savings Balance
        """
        pass

    def test_get_savings_history_savings_history_get(self) -> None:
        """Test case for get_savings_history_savings_history_get

        Get Savings History
        """
        pass

    def test_list_saving_goals_savings_get(self) -> None:
        """Test case for list_saving_goals_savings_get

        List Saving Goals
        """
        pass

    def test_withdraw_from_savings_savings_withdraw_post(self) -> None:
        """Test case for withdraw_from_savings_savings_withdraw_post

        Withdraw From Savings
        """
        pass


if __name__ == '__main__':
    unittest.main()
