# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.budget_api import BudgetApi


class TestBudgetApi(unittest.TestCase):
    """BudgetApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BudgetApi()

    def tearDown(self) -> None:
        pass

    def test_budget_status_budget_status_get(self) -> None:
        """Test case for budget_status_budget_status_get

        Budget Status
        """
        pass

    def test_set_budget_budget_post(self) -> None:
        """Test case for set_budget_budget_post

        Set Budget
        """
        pass


if __name__ == '__main__':
    unittest.main()
