# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.health_api import HealthApi


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthApi()

    def tearDown(self) -> None:
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass


if __name__ == '__main__':
    unittest.main()
