# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dashboard_out import DashboardOut

class TestDashboardOut(unittest.TestCase):
    """DashboardOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardOut:
        """Test DashboardOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardOut`
        """
        model = DashboardOut()
        if include_optional:
            return DashboardOut(
                total_income = 1.337,
                total_expenses = 1.337,
                balance = 1.337,
                total_savings = 1.337,
                monthly_income = 1.337,
                monthly_expenses = 1.337,
                carried_savings = 1.337,
                total_transactions = 56,
                top_spending_category = '',
                recent_activity = [
                    openapi_client.models.transaction_out.TransactionOut(
                        id = 56, 
                        amount = 1.337, 
                        description = '', 
                        transaction_type = '', 
                        category = '', 
                        auto_tagged = True, 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        note = '', )
                    ]
            )
        else:
            return DashboardOut(
                total_income = 1.337,
                total_expenses = 1.337,
                balance = 1.337,
                total_savings = 1.337,
                monthly_income = 1.337,
                monthly_expenses = 1.337,
                carried_savings = 1.337,
                total_transactions = 56,
                top_spending_category = '',
                recent_activity = [
                    openapi_client.models.transaction_out.TransactionOut(
                        id = 56, 
                        amount = 1.337, 
                        description = '', 
                        transaction_type = '', 
                        category = '', 
                        auto_tagged = True, 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        note = '', )
                    ],
        )
        """

    def testDashboardOut(self):
        """Test DashboardOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
