# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.reclassify_request import ReclassifyRequest

class TestReclassifyRequest(unittest.TestCase):
    """ReclassifyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReclassifyRequest:
        """Test ReclassifyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReclassifyRequest`
        """
        model = ReclassifyRequest()
        if include_optional:
            return ReclassifyRequest(
                category = ''
            )
        else:
            return ReclassifyRequest(
                category = '',
        )
        """

    def testReclassifyRequest(self):
        """Test ReclassifyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
