# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recurring_out import RecurringOut

class TestRecurringOut(unittest.TestCase):
    """RecurringOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecurringOut:
        """Test RecurringOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecurringOut`
        """
        model = RecurringOut()
        if include_optional:
            return RecurringOut(
                id = 56,
                description = '',
                amount = 1.337,
                transaction_type = '',
                category = '',
                frequency = '',
                next_due_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return RecurringOut(
                id = 56,
                description = '',
                amount = 1.337,
                transaction_type = '',
                category = '',
                frequency = '',
        )
        """

    def testRecurringOut(self):
        """Test RecurringOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
