# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ai_integration_api import AIIntegrationApi


class TestAIIntegrationApi(unittest.TestCase):
    """AIIntegrationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AIIntegrationApi()

    def tearDown(self) -> None:
        pass

    def test_chat_assistant_ai_chat_post(self) -> None:
        """Test case for chat_assistant_ai_chat_post

        Chat Assistant
        """
        pass

    def test_chat_assistant_ai_chatbot_query_post(self) -> None:
        """Test case for chat_assistant_ai_chatbot_query_post

        Chat Assistant
        """
        pass

    def test_parse_receipt_ai_receipt_post(self) -> None:
        """Test case for parse_receipt_ai_receipt_post

        Parse Receipt
        """
        pass


if __name__ == '__main__':
    unittest.main()
