# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.budget_status import BudgetStatus

class TestBudgetStatus(unittest.TestCase):
    """BudgetStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BudgetStatus:
        """Test BudgetStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BudgetStatus`
        """
        model = BudgetStatus()
        if include_optional:
            return BudgetStatus(
                category = '',
                monthly_limit = 1.337,
                current_spending = 1.337,
                projected_spending = 1.337,
                days_left = 56,
                exceeded = True
            )
        else:
            return BudgetStatus(
                category = '',
                monthly_limit = 1.337,
                current_spending = 1.337,
                projected_spending = 1.337,
                days_left = 56,
                exceeded = True,
        )
        """

    def testBudgetStatus(self):
        """Test BudgetStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
