# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.recurring_api import RecurringApi


class TestRecurringApi(unittest.TestCase):
    """RecurringApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecurringApi()

    def tearDown(self) -> None:
        pass

    def test_create_recurring_recurring_post(self) -> None:
        """Test case for create_recurring_recurring_post

        Create Recurring
        """
        pass

    def test_delete_recurring_recurring_rec_id_delete(self) -> None:
        """Test case for delete_recurring_recurring_rec_id_delete

        Delete Recurring
        """
        pass

    def test_list_recurring_recurring_get(self) -> None:
        """Test case for list_recurring_recurring_get

        List Recurring
        """
        pass


if __name__ == '__main__':
    unittest.main()
