# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gamification_status import GamificationStatus

class TestGamificationStatus(unittest.TestCase):
    """GamificationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GamificationStatus:
        """Test GamificationStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GamificationStatus`
        """
        model = GamificationStatus()
        if include_optional:
            return GamificationStatus(
                streak_days = 56,
                badges = [
                    openapi_client.models.badge.Badge(
                        name = '', 
                        icon = '', 
                        description = '', 
                        unlocked = True, )
                    ],
                savings_progress = 1.337
            )
        else:
            return GamificationStatus(
                streak_days = 56,
                badges = [
                    openapi_client.models.badge.Badge(
                        name = '', 
                        icon = '', 
                        description = '', 
                        unlocked = True, )
                    ],
                savings_progress = 1.337,
        )
        """

    def testGamificationStatus(self):
        """Test GamificationStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
