# coding: utf-8

"""
    Personal Finance Tracker

    Track income, expenses, budgets, and recurring transactions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.optimization_recommendation import OptimizationRecommendation

class TestOptimizationRecommendation(unittest.TestCase):
    """OptimizationRecommendation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OptimizationRecommendation:
        """Test OptimizationRecommendation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OptimizationRecommendation`
        """
        model = OptimizationRecommendation()
        if include_optional:
            return OptimizationRecommendation(
                category = '',
                count = 56,
                potential_monthly_savings = 1.337,
                message = ''
            )
        else:
            return OptimizationRecommendation(
                category = '',
                count = 56,
                potential_monthly_savings = 1.337,
                message = '',
        )
        """

    def testOptimizationRecommendation(self):
        """Test OptimizationRecommendation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
